Fcsk

diff --git a/apply-a-definition/check-kubernetes b/apply-a-definition/check-kubernetes
--- a/apply-a-definition/check-kubernetes
+++ b/apply-a-definition/check-kubernetes
@@ -1,1 +1,15 @@
 #!/bin/bash
+COMMAND=$(cat /root/.bash_history | grep -e "^kubectl apply -f" -e "^kubectl create -f" | wc -l)
+if [ $COMMAND -eq 0 ]; then
+  echo "FAIL: The kubectl apply definition command was not run."
+  exit 1
+fi
+
+POD=$(kubectl get pod nginx --output json)
+# Check if we have a result
+if [ $? == 1 ]; then
+  echo "FAIL: There was no pod called nginx"
+  exit 1
+fi
+
+exit 0
diff --git a/definition-files/check-kubernetes b/definition-files/check-kubernetes
--- a/definition-files/check-kubernetes
+++ b/definition-files/check-kubernetes
@@ -1,1 +1,15 @@
 #!/bin/bash
+set -e
+
+if [ ! -f "/tmp/nginx-yml-touched" ]; then
+  echo "FAIL: The nginx.yml file was not accessed"
+  exit 1
+fi
+
+ACCESS=$(grep ACCESS /tmp/nginx-yml-touched | wc -l)
+if [ $ACCESS -eq 0 ]; then
+  echo "FAIL: The nginx.yml file was not accessed"
+  exit 1
+fi
+
+exit 0
diff --git a/delete-a-definition/check-kubernetes b/delete-a-definition/check-kubernetes
--- a/delete-a-definition/check-kubernetes
+++ b/delete-a-definition/check-kubernetes
@@ -1,1 +1,15 @@
 #!/bin/bash
+COMMAND=$(cat /root/.bash_history | grep "^kubectl delete -f" | wc -l)
+if [ $COMMAND -eq 0 ]; then
+  echo "FAIL: The kubectl delete definition command was not run."
+  exit 1
+fi
+
+POD=$(kubectl get pod nginx --output json)
+# Check if we have a result
+if [ $? == 0 ]; then
+  echo "FAIL: The pod named nginx was not removed. Hint: check if its still terminating with kubectl get pods"
+  exit 1
+fi
+
+exit 0
diff --git a/edit-a-definition/check-kubernetes b/edit-a-definition/check-kubernetes
--- a/edit-a-definition/check-kubernetes
+++ b/edit-a-definition/check-kubernetes
@@ -1,1 +1,22 @@
 #!/bin/bash
+COMMAND=$(cat /root/.bash_history | grep "^kubectl edit pod/" | wc -l)
+if [ $COMMAND -eq 0 ]; then
+  echo "FAIL: The kubectl edit definition command was not run."
+  exit 1
+fi
+
+POD=$(kubectl get pod nginx --output json)
+# Check if we have a result
+if [ $? == 1 ]; then
+  echo "FAIL: There was no pod called nginx"
+  exit 1
+fi
+
+
+IMAGE=$(echo $POD | jq -r '.spec.containers[0].image')
+if [ "$IMAGE" != "nginx:1.13.8-alpine" ]; then
+  echo "FAIL: Wrong image of nginx found on pod nginx: expected nginx:1.13.8-alpine but found $IMAGE"
+  exit 1
+fi
+
+exit 0
diff --git a/multiple-containers/check-kubernetes b/multiple-containers/check-kubernetes
--- a/multiple-containers/check-kubernetes
+++ b/multiple-containers/check-kubernetes
@@ -1,1 +1,15 @@
 #!/bin/bash
+POD=$(kubectl get pod nginx --output json)
+# Check if we have a result
+if [ $? == 1 ]; then
+  echo "FAIL: There was no pod called nginx"
+  exit 1
+fi
+
+CONTAINERS=$(echo $POD | jq -r '.spec.containers | length')
+if [ $CONTAINERS != 2 ]; then
+  echo "FAIL: Expected 2 containers in pod nginx: found $CONTAINERS"
+  exit 1
+fi
+
+exit 0
diff --git a/remove-an-application/check-kubernetes b/remove-an-application/check-kubernetes
--- a/remove-an-application/check-kubernetes
+++ b/remove-an-application/check-kubernetes
@@ -1,1 +1,10 @@
 #!/bin/bash
+DEPLOYMENT=$(kubectl get deployments nginx)
+
+# Check if we have a result
+if [ $? == 0 ]; then
+  echo "FAIL: The deployment named nginx was not removed"
+  exit 1
+fi
+
+exit 0
diff --git a/run-an-application/check-kubernetes b/run-an-application/check-kubernetes
--- a/run-an-application/check-kubernetes
+++ b/run-an-application/check-kubernetes
@@ -1,1 +1,23 @@
 #!/bin/bash
+DEPLOYMENT=$(kubectl get deployments nginx --output json)
+
+# Check if we have a result
+if [ $? == 1 ]; then
+  echo "FAIL: There was no deployment called nginx"
+  exit 1
+fi
+
+CONTAINER=$(echo $DEPLOYMENT | jq -r .spec.template.spec.containers[0])
+IMAGE=$(echo $CONTAINER | jq -r .image)
+if [ "$IMAGE" != "nginx" ]; then
+  echo "FAIL: The image of the nginx deployment incorrect: expected nginx but found $IMAGE"
+  exit 1
+fi
+
+PORT=$(echo $CONTAINER | jq -r .ports[0].containerPort)
+if [ "$PORT" != "80" ]; then
+  echo "FAIL: The deployment does not have the correct port defined: expected 80 but found $PORT"
+  exit 1
+fi
+
+exit 0
